[package]
name = "fopener-gui-fltk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fopener-gui"
path = "src/main.rs"

[dependencies]
fopener-core = { path = "../fopener-core" }
fopener-config = { path = "../fopener-config" }
fopener-watcher = { path = "../fopener-watcher" }
fopener-actions = { path = "../fopener-actions" }
fltk = { version = "1", features = ["fltk-bundled"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = "0.4"
regex = { workspace = true }
